language: ruby
before_script:
  - sudo apt-get update
  - sudo apt-get install cmake
  - git clone https://github.com/CastXML/CastXML.git
  - mkdir CastXMLBuild
  - cd CastXMLBuild
  - cmake ../CastXML
  - make
  - export PATH=$PWD/bin:$PATH
  - cd ..
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
