language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install cmake
  - gem install bundler
  - git clone https://github.com/CastXML/CastXML.git
  - mkdir CastXMLBuild
  - cd CastXMLBuild
  - cmake ../CastXML
  - make
  - export PATH=$PWD/bin:$PATH
  - cd ..
rvm:
  - 2.2
  - 2.3
  - 2.4
